name: backend_sign_in
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  shelf: ^1.1.2
  shelf_router: ^1.0.0
  mysql1: ^0.19.2
  jaguar_jwt: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  shelf_router_generator: ^1.0.0
  build_runner: ^2.0.3
  test: ^1.18.2
  mocktail: ^0.2.0
